CREATE TABLE `properties` (
  `id` INT(11) NOT NULL,
  `key` VARCHAR(50) DEFAULT NULL,
  `value` VARCHAR(500) DEFAULT NULL,
  `application` VARCHAR(50) DEFAULT NULL,
  `profile` VARCHAR(50) DEFAULT NULL,
  `label` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8