server:
  port: 8764

spring:
  application:
    name: auth-service

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/