server:
  port: 8761

spring:
  application:
    name: cloud-eureka

eureka:
  instance:
    hostname: localhost
    #  服务续约（心跳）频率，单位：秒，缺省30
    lease-renewal-interval-in-seconds: 5
  server:
    # Eureka服务器清理无效节点的时间间隔，单位：毫秒，缺省：60000，即60秒
    eviction-interval-timer-in-ms: 5000
    # 是否开启保护机制，默认true
    enable-self-preservation: false
    # 默认30s. eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，
    # 这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    response-cache-update-interval-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
