server:
  port: 8765

spring:
  application:
    name: zuul
  cloud:
    loadbalancer:
      retry:
        # 该参数用来开启重试机制，默认是关闭
        enabled: true


eureka:
  instance:
    hostname: localhost
    # 设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    # 客户端拉取服务注册信息间隔，单位：秒，缺省：30
    registry-fetch-interval-seconds: 5
    # Eureka服务端连接空闲时的关闭时间，单位：秒，缺省：30
    eureka-connection-idle-timeout-seconds: 30
    # 连接Eureka服务器的超时时间，单位：秒，缺省：5
    eureka-server-connect-timeout-seconds: 5
    # 从Eureka服务器读取信息的超时时间，单位：秒，缺省：8
    eureka-server-read-timeout-seconds: 8
zuul:
  routes:
    park-service:
      path: /park-service/**
      serviceId: park-service
  host:
    socket-timeout-millis: 1000
    connect-timeout-millis: 1000
  retryable: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


ribbon:
#  eureka:
#    enable: false
  ReadTimeout: 1000
  ConnectTimeout: 1000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 1


park-service:
  ribbon:
    listOfServers: http://localhost:8762
